apis:
  ticket:
    url:  http://associateservice:8080/api/associados

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://ticketdb:5435/UNICRED_BOLETO
    username: root
    kafka:
      bootstrap-servers: http://kafka:29092