topics:
  create-ticket: create-ticket

apis:
  associate:
    url: http://associateservice:8080/api/associados

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5433/UNICRED_BOLETO
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_URI:kafka:29092}
    properties:
      security.protocol: PLAINTEXT
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: "unicred-payment"
      client-id: "unicred-payment"
      max.poll.records: 500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual_immediate
      concurrency: 15
    topics:
      create-ticket:
        partitions: 10
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB

server:
  servlet:
    context-path: /api
  port: 8081