apis:
  ticket:
    url: http://localhost:8081/api/boletos

topics:
  create-ticket: create-ticket

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5432/UNICRED_ASSOCIADO
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: http://localhost:29092
    properties:
      security.protocol: PLAINTEXT
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      max-poll-records: 1
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: "unicred-payment"
      client-id: "unicred-payment"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual_immediate
server:
  servlet:
    context-path: /api
